# Generated by Django 4.1.6 on 2023-02-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
