# Generated by Django 4.1.6 on 2023-02-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0004_brand_category_color_size_unit_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
