# Generated by Django 4.1.6 on 2023-03-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0009_qtyupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtyupdatelog',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_apps.product'),
        ),
    ]
