# Generated by Django 4.1.6 on 2023-03-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0010_qtyupdatelog_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPriceUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_sales_price', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_apps.product')),
            ],
            options={
                'db_table': 'sales_price_update_log',
            },
        ),
    ]
