# Generated by Django 4.1.6 on 2023-03-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0012_regularpriceupdatelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentactivitylog',
            old_name='department',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='departmentactivitylog',
            old_name='activity_type',
            new_name='updated_department_name',
        ),
        migrations.RenameField(
            model_name='departmentactivitylog',
            old_name='activity_timestamp',
            new_name='updated_time',
        ),
    ]
