# Generated by Django 4.1.6 on 2023-03-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0013_rename_department_departmentactivitylog_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentactivitylog',
            old_name='department_name',
            new_name='department',
        ),
    ]
