# Generated by Django 4.1.6 on 2023-03-02 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0015_brandactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_unit_name', models.CharField(max_length=50)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_apps.unit')),
            ],
            options={
                'db_table': 'unit_activity_log',
            },
        ),
    ]
