# Generated by Django 4.1.6 on 2023-03-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apps', '0016_unitactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_size_name', models.CharField(max_length=50)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('size_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_apps.size')),
            ],
            options={
                'db_table': 'size_activity_log',
            },
        ),
        migrations.CreateModel(
            name='ColorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_color_name', models.CharField(max_length=50)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('color_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_apps.color')),
            ],
            options={
                'db_table': 'color_activity_log',
            },
        ),
        migrations.CreateModel(
            name='CategoryActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_category_name', models.CharField(max_length=50)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_apps.category')),
            ],
            options={
                'db_table': 'category_activity_log',
            },
        ),
    ]
