# Generated by Django 4.1.6 on 2023-03-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=50)),
                ('customer_phone', models.CharField(max_length=14)),
                ('customer_address', models.TextField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
