# Generated by Django 4.1.6 on 2023-03-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.district'),
        ),
        migrations.AddField(
            model_name='customers',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.division'),
        ),
        migrations.AddField(
            model_name='customers',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.thana'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_address',
            field=models.CharField(max_length=255),
        ),
    ]
